### ISSUE TITLE
So much FLAC

### ISSUE THREAD

**Issue by yaskhan** [sourrust/flac#1]
https://github.com/search?utf8=%E2%9C%93&q=language%3Arust+flac

**Comment by sourrust** [comment]
I don't really consider this to be a problem. The reason I started this project was to learn about audio codecs. Having more than one project crop up looks there is some need for audio codes written purely in Rust. Of those nine I could see that about two, not including mine, that are active and adjacent to what I'm doing, which is perfectly fine. Of course claxon is the one most complete since it has a full decoder working. However, I don't plan to stop at only decoding FLAC, so there is something unique about this project.
